update-store-retargetting-data
trackier/android_sdk pull request #67
Opened 2024-01-29 05:42 UTC by IloveJavaa

Stored the retargetting data.
Asana link - https://app.asana.com/0/0/1206458202841357/f

2024-01-31 14:17 UTC, Hemant-Mann requested changes
fix retargeting word

2024-01-31 14:17 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/Constants.kt
> +    const val STORE_RETARGETTING = "retargetting"
```suggestion
    const val STORE_RETARGETING = "retargeting"
```

2024-01-31 14:18 UTC, Hemant-Mann requested changes

2024-01-31 14:18 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/Util.kt
> +        body["date&time"] = time
key name should not have &

```suggestion
        body["rtgtime"] = time
```

2024-01-31 14:18 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierWorkRequest.kt
> +        body["storeRetargetting"] = Util.retargettingData(storeRetargetting, Util.dateFormatter.format(Date()))
why are you sending the current time here?

2024-01-31 14:18 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDK.kt
> +        Util.setSharedPrefString(ctx, Constants.STORE_RETARGETTING, uri)
when storing the retargeting info here you have to store the time as well

2024-02-01 05:56 UTC, IloveJavaa commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/Constants.kt
> +    const val STORE_RETARGETTING = "retargetting"
Fixed

2024-02-01 05:57 UTC, IloveJavaa commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/Util.kt
> +        body["date&time"] = time
fixed

2024-02-01 14:12 UTC, IloveJavaa commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierWorkRequest.kt
> +        body["storeRetargetting"] = Util.retargettingData(storeRetargetting, Util.dateFormatter.format(Date()))
I have changed this from here now

2024-02-01 15:40 UTC, Hemant-Mann requested changes
changes needed

2024-02-01 15:40 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDKInstance.kt
> +        return body.toString()
return body as it is @IloveJavaa

2024-02-01 16:10 UTC, IloveJavaa commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDKInstance.kt
> +        return body.toString()
done

2024-02-01 16:14 UTC, Hemant-Mann approved these changes

2024-02-01 16:14 UTC, merged