feat-dynamic-deeplinks-support
trackier/android_sdk pull request #70
Opened 2024-02-28 18:18 UTC by IloveJavaa

Added code for dynamic deeplinks
Asana task - https://app.asana.com/0/0/1206702369644644/f

2024-03-03 15:27 UTC, Hemant-Mann requested changes

2024-03-03 15:27 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/APIRepository.kt
> +        logger.info("Deeplinks body is: $body")
Remove this

2024-03-03 15:27 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDK.kt
> +    fun parseDeepLink(uri: Uri?, context: Context) {
Uri can not be null

2024-03-03 15:27 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/ResponseData.kt
> +data class Data(
Let's rename it to DlData class

2024-03-03 15:27 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDK.kt
> -        prefs.edit().putString(Constants.SHARED_PREF_DEEP_LINK, uri.query)
Yeh sara code instance waali class mein kove kardo

2024-03-03 15:27 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDKInstance.kt
> +        if (dlObj.data?.url == null){
Again it can not be null

2024-03-03 15:32 UTC, IloveJavaa commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/ResponseData.kt
> +data class Data(
done

2024-03-03 16:59 UTC, IloveJavaa commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDK.kt
> -        prefs.edit().putString(Constants.SHARED_PREF_DEEP_LINK, uri.query)
done

2024-03-04 06:30 UTC, IloveJavaa commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDK.kt
> +    fun parseDeepLink(uri: Uri?, context: Context) {
done

2024-03-04 06:30 UTC, IloveJavaa commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDKInstance.kt
> +        if (dlObj.data?.url == null){
done

2024-03-04 07:12 UTC, IloveJavaa commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/APIRepository.kt
> +        logger.info("Deeplinks body is: $body")
done

2024-03-04 08:36 UTC, Hemant-Mann requested changes

2024-03-04 08:36 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDK.kt
> +import kotlinx.coroutines.CoroutineScope
remove these imports as no longer used

2024-03-04 08:36 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDK.kt
> +        uri ?: return
plz use if statement for return

2024-03-04 08:36 UTC, Hemant-Mann commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDKInstance.kt
> +    fun parseDeepLink(uri: Uri) {
use uri: Uri?

2024-03-04 08:38 UTC, IloveJavaa commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDK.kt
> +import kotlinx.coroutines.CoroutineScope
done

2024-03-04 08:38 UTC, IloveJavaa commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDKInstance.kt
> +    fun parseDeepLink(uri: Uri) {
done

2024-03-04 08:40 UTC, IloveJavaa commented on TrackierSDK/sdk-core/src/main/java/com/trackier/sdk/TrackierSDK.kt
> +        uri ?: return
done

2024-03-04 08:47 UTC, Hemant-Mann approved these changes

2024-03-04 08:48 UTC, merged